apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "severus-ai.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "severus-ai.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "severus-ai.name" . }}
    spec:
      containers:
        - name: severus-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: OLLAMA_BASE_URL
              value: "{{ .Values.env.OLLAMA_BASE_URL }}"
