apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "severus-ai.fullname" . }}
  labels:
    {{- include "severus-ai.labels" . | nindent 4 }}
    app.kubernetes.io/name: severus-ai
    app.kubernetes.io/part-of: observability-demo

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: severus-ai
      app.kubernetes.io/name: severus-ai

  template:
    metadata:
      labels:
        app: severus-ai
        app.kubernetes.io/name: severus-ai
        app.kubernetes.io/part-of: observability-demo

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: "/metrics"

    spec:
      containers:
        - name: severus-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
