apiVersion: v1
kind: Service
metadata:
  name: {{ include "severus-ai.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "severus-ai.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
