apiVersion: v1
kind: Service
metadata:
  name: {{ include "severus-ai.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "severus-ai.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
