apiVersion: v1
kind: Service
metadata:
  name: {{ include "severus-ai.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: severus-ai
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
